trigger: [ master ]
pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - task: Bash@3
    inputs:
      targetType: inline
      script: echo 'Hello, world!'
  - task: CopyFiles@2
    inputs:
      contents: 'policies\**\*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: policies
      publishLocation: Container
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - task: PythonScript@0
    displayName: 'Validate policies'
    inputs:
      scriptSource: 'filePath'
      scriptPath: "src/build/scripts/validate_policy_mode.py"
      arguments: '-d changed-files.json'
      failOnStderr: true