trigger: [ master ]
pool:
  vmImage: 'Ubuntu 16.04'
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - task: Bash@3
    inputs:
      targetType: inline
      script: echo 'Hello, world!'
  - task: CopyFiles@2
    inputs:
      contents: 'policies\**\*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: policies
      publishLocation: Container
