name: Cloud Custodian - CI
trigger:
  branches:
    include:
    - master
pool:
  vmImage: 'Ubuntu 16.04'

# Variables to use in build tasks
variables:
  serviceConnectionAzureSubscription: nameOfTheServiceConnection # replace with Azure DevOps Azure ARM service connection name
  keyVaultName: nameOfKeyVault # replace with name of KeyVault used to store CI/CD pipeline secrets
  secretsFilter: '*' # replace with name of secret or * for all secrets
  modifiedPoliciesFilePath: policies/modified.yml # replace with name of yml file containing all policies that have been modified and need to be validated
  configFilePath: policies/config.json # replace with path to policy config file if not default
  policyFilePath: policies/policies.build.json # replace with path to policy file if not default
  outputPath: output # replace with path for Custodian policy run output
  repositoryId: idOfTheRepository # replace with the id of the repository, see Project Settings -> Repositories -> Select repo and look at URL
  cloudCustodianCommit: 9f521de6a7cc30394fd4627a4c63e41a23424b9a # Cloud Custodian commit to use

# Build tasks
steps:
  - template: buildSteps/custodianBuildSteps.yml
    parameters:
      serviceConnectionAzureSubscription: $(serviceConnectionAzureSubscription)
      keyVaultName: $(keyVaultName)
      secretsFilter: $(secretsFilter)
      modifiedPoliciesFilePath: $(modifiedPoliciesFilePath)
      configFilePath: $(configFilePath)
      policyFilePath: $(policyFilePath)
      outputPath: $(outputPath)
      cloudCustodianCommit: $(cloudCustodianCommit)

# Copy Cloud Custodian dryrun output files
  - task: CopyFiles@2
    displayName: 'Copy Cloud Custodian dryrun output files'
    inputs:
      contents: 'output/**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  # Copy configuration files
  - task: CopyFiles@2
    displayName: 'Copy configuration files'
    inputs:
      contents: 'policies/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  # Copy deployment scripts
  - task: CopyFiles@2
    displayName: 'Copy deployment scripts'
    inputs:
      contents: 'src/build/scripts/policy_runner.py'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  # Copy policies
  - task: CopyFiles@2
    displayName: 'Copy policies'
    inputs:
      contents: '*.yml'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  # Remove azure-pipelines.yml from build artifacts
  - task: DeleteFiles@1
    displayName: 'Remove azure-pipelines.yml from build artifacts'
    inputs:
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: azure-pipelines.yml

  # Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: package
      publishLocation: Container
